// <auto-generated />
using System;
using CasaVintage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaVintage.Migrations
{
    [DbContext(typeof(CasaVintageContext))]
    [Migration("20260729140511_AgregarTarjetaUltimos4")]
    partial class AgregarTarjetaUltimos4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasaVintage.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("CasaVintage.Models.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("detalle_venta", null, t =>
                        {
                            t.HasCheckConstraint("CK_detalle_cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("CasaVintage.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit")
                        .HasColumnName("disponibilidad");

                    b.Property<string>("Epoca")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("epoca");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Foto1")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto1");

                    b.Property<string>("Foto2")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto2");

                    b.Property<string>("Foto3")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto3");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_minimo");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UQ_productos_sku");

                    b.ToTable("productos", null, t =>
                        {
                            t.HasCheckConstraint("CK_productos_costo", "costo >= 0");

                            t.HasCheckConstraint("CK_productos_precio", "precio >= 0");

                            t.HasCheckConstraint("CK_productos_stock", "stock >= 0");
                        });
                });

            modelBuilder.Entity("CasaVintage.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Contacto")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("CasaVintage.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creado")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_usuarios_correo");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuarios_rol", "rol IN ('Administrador','Gerente','Vendedor','Contador')");
                        });
                });

            modelBuilder.Entity("CasaVintage.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("TarjetaUltimos4")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("tarjeta_ultimos4");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_pagado");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ventas", null, t =>
                        {
                            t.HasCheckConstraint("CK_ventas_metodo", "metodo_pago IN ('Efectivo','Tarjeta')");
                        });
                });

            modelBuilder.Entity("CasaVintage.Models.DetalleVenta", b =>
                {
                    b.HasOne("CasaVintage.Models.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_detalle_producto");

                    b.HasOne("CasaVintage.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_detalle_venta");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CasaVintage.Models.Producto", b =>
                {
                    b.HasOne("CasaVintage.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_productos_proveedor");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("CasaVintage.Models.Venta", b =>
                {
                    b.HasOne("CasaVintage.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ventas_cliente");

                    b.HasOne("CasaVintage.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ventas_usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CasaVintage.Models.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("CasaVintage.Models.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CasaVintage.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CasaVintage.Models.Usuario", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("CasaVintage.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
